### ISSUE TITLE
base directory for PLUGINS

### ISSUE THREAD

**Issue by greenkrd** [iDebugAll/nextbox-ui-plugin#10]
Hi, we have recently insatlled netbox 2.8.4, in that version plugins directory moved to "project-static", so after installation of nextbox-ui-plugin we have copied all content from "static" directory to "project-static" and it works with some issues (not showing some icons, "hide passive" didnt work, broken font), so I think problem that some files had not correct link to directories

**Comment by iDebugAll** [comment]
Please try to install the [latest version](https://pypi.org/project/nextbox-ui-plugin/).
All links on the topology page are now rendered from the {% static %} template.
