### ISSUE TITLE
Topology viewer showing nothing

### ISSUE THREAD

**Issue by Kniickk** [iDebugAll/nextbox-ui-plugin#107]
Hello,

i have installed nextbox and it dosent show anything in the Topology view.
Below the Ooutput from the Consol, i know this error was alredy Discussed here #91 but i dont know what resolved it.
I am new to this and i hope somone can help me with it.

![grafik](https://user-images.githubusercontent.com/110382963/182568216-d3ac1e8f-aec6-4576-a45c-33f2d1d13ec8.png)

If you need more info just let me know

**Comment by Kniickk** [comment]
I solved it myself after looking for a bit deeper.
I needed to change a  COPY command in the Dockerfile of nextbox. 
It was clearer after i found the Post #68

**Comment by Kniickk** [comment]
Now i get a jquerry Error when opening the Topology viewer.
![grafik](https://user-images.githubusercontent.com/110382963/182577716-d592ef26-9eef-4505-94dc-6a2457f39d27.png)

Any idea waht this could be?

**Comment by PaulR282** [comment]
My console looks the same but the viewer works. Does the viewer not show up or just no devices? (Do you have the tools on the left side?) If you see the tools, try to go to "Filter" and just click search with nothing selected/changed. The plugin needs some sort of filter in the URL. Already addressed this problem in #87

**Comment by Kniickk** [comment]
If this s normal then okay, in the Region Section it kinda works.

But if i go under the Plugins Topology viewer it doesn't and i get the following.

![grafik](https://user-images.githubusercontent.com/110382963/183674331-71545aba-c2d7-4118-a447-8452a00fafa4.png)

and nothing is displayed and i can't click anything

**Comment by PaulR282** [comment]
Did you do a `manage.py collectstatic`?

**Comment by Kniickk** [comment]
So i installed it in a Docker Container. If i do a collect static it shows me the following:
![grafik](https://user-images.githubusercontent.com/110382963/183832674-85adc9ea-8b23-4de8-af35-f702e4d32391.png)

**Comment by PaulR282** [comment]
Yeah, I'm also struggling at that point. For me, the plugin works but I also can't collect static files (needed for another plugin) because of the same error.

**Comment by iDebugAll** [comment]
In Docker deployment you can specify root user for your exec session. It should allow you to collect static without permission issues: ```% docker-compose exec -u root netbox /bin/bash```
And then ```# ./manage.py collectstatic``` plus ```# chown 1000:1000 -R /opt/netbox/netbox/static/nextbox_ui_plugin/```
