### ISSUE TITLE
Plugin broken in Netbox 3.3

### ISSUE THREAD

**Issue by dreng** [iDebugAll/nextbox-ui-plugin#108]
After hitting the search button you get an error:

<class 'django.core.exceptions.FieldError'>

Cannot resolve keyword '_termination_a_device_id' into field. Choices are: _abs_length, color, created, custom_field_data, id, journal_entries, label, last_updated, length, length_unit, status, tagged_items, tags, tenant, tenant_id, terminations, type

Python version: 3.9.2
NetBox version: 3.3.0

**Comment by RR3US** [comment]
+1 same error:
`<class 'django.core.exceptions.FieldError'>

Cannot resolve keyword '_termination_a_device_id' into field. Choices are: _abs_length, color, created, custom_field_data, id, journal_entries, label, last_updated, length, length_unit, status, tagged_items, tags, tenant, tenant_id, terminations, type

Python version: 3.10.6
NetBox version: 3.3.5`

**Comment by reiters-it** [comment]
also this error:

FieldError at /plugins/nextbox-ui/site_topology/

Cannot resolve keyword '_termination_a_device_id' into field. Choices are: _abs_length, color, created, custom_field_data, id, journal_entries, label, last_updated, length, length_unit, status, tagged_items, tags, tenant, tenant_id, terminations, type

Request Method:	GET
Request URL:	https://sub.domain.tld/plugins/nextbox-ui/site_topology/?site_id=6
Django Version:	4.0.8
Exception Type:	FieldError
Exception Value:	
Cannot resolve keyword '_termination_a_device_id' into field. Choices are: _abs_length, color, created, custom_field_data, id, journal_entries, label, last_updated, length, length_unit, status, tagged_items, tags, tenant, tenant_id, terminations, type
Exception Location:	/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/sql/query.py, line 1677, in names_to_path
Python Executable:	/opt/netbox/venv/bin/python3
Python Version:	3.8.10
Python Path:	
['/opt/netbox/netbox',
 '/opt/netbox',
 '/opt/netbox/venv/bin',
 '/usr/lib/python38.zip',
 '/usr/lib/python3.8',
 '/usr/lib/python3.8/lib-dynload',
 '/opt/netbox/venv/lib/python3.8/site-packages']

**Comment by Qwiko** [comment]
I have the same issue on version 3.3.5.
Version 3.3.0 changed some internal variables which broke this plugin.

**Comment by BDNS-NETBOX** [comment]
When will this be fixed, are they working on this?

**Comment by Qwiko** [comment]
I have tried to solve some of the bugs with this plugin.
Works fairly well with netbox version 3.3 and above.
The display topology does not error out.
There are still alot of small bugs with CSS styling and the Save Current View function.
https://github.com/Qwiko/nextbox-ui-plugin

**Comment by geniesis** [comment]
Using @Qwiko patch it still errors on when there are power connections.

`   File "/opt/netbox/venv/lib/python3.10/site-packages/nextbox_ui_plugin/views.py", line 499, in get
     topology_dict, device_roles, multi_cable_connections, device_tags = get_topology(self.queryset)
   File "/opt/netbox/venv/lib/python3.10/site-packages/nextbox_ui_plugin/views.py", line 377, in get_topology
     if b_termination.device_id in device_ids:
   AttributeError: 'PowerFeed' object has no attribute 'device_id'`

**Comment by Qwiko** [comment]
@geniesis I now filtered out PowerFeed cabling and that should resolve the issue.
A PowerFeed does not have a Device id and can't be displayed.

**Comment by dreng** [comment]
As there is no reaction at all since two months, I suppose this project is not being maintained anymore. There are also other major bugs open that are even older. I have therefore switched to [netbox-topology-views](https://github.com/mattieserver/netbox-topology-views), which (in my optinion) became a better replacement in the meantime  anyway.

**Comment by mikesrus** [comment]
how to correctly remove this plugin? i switch to https://github.com/mattieserver/netbox-topology-views too.

**Comment by iDebugAll** [comment]
Hi everyone. 

Sorry for not responding so much time. I was immigrating to another country and rebuilding by life.
Hopefully I'll return to the plugin development and fix this compatibility issue soon.

**Comment by mikesrus** [comment]
> Hi everyone.
> 
> Sorry for not responding so much time. I was immigrating to another country and rebuilding by life. Hopefully I'll return to the plugin development and fix this compatibility issue soon.

эх.. а кому щас легко. Удачи на новом месте :)

**Comment by iDebugAll** [comment]
Hey. New plugin version v0.10.0 fixes compatibility issue with NetBox 3.3. It's already available here and on PyPI.
