### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by Ixxtiander** [iDebugAll/nextbox-ui-plugin#109]
<class 'django.db.utils.ProgrammingError'>

ОШИБКА:  отношение "nextbox_ui_plugin_savedtopology" не существует
LINE 1: ...nextbox_ui_plugin_savedtopology"."timestamp" FROM "nextbox_u...
                                                             ^

Python version: 3.8.10
NetBox version: 3.3.0

**Comment by Qwiko** [comment]
See #108
