### ISSUE TITLE
Running in Docker behind reverse proxy does not work 

### ISSUE THREAD

**Issue by ziggekatten** [iDebugAll/nextbox-ui-plugin#11]
We are running netbox behind a reverse proxy (Traefik) with a URL rewrite. This is how we access Netbox:

URL: https://server.bogus.net/ipam/

Now, installing the plugin per instruction works, and logging into netbox, I get the topology button, so it loads the plugin.

However, it seems that the wrong path is being used as the plugin is not proxy aware, as the popup loads with a 404 page not found error. 
![image](https://user-images.githubusercontent.com/55629049/83967820-36d25880-a8c5-11ea-8cbc-5b2da4fb3514.png)

Looking in Chrome, the path used are: 

https://server.bogus.net/plugins/nextbox-ui/site_topology/1/

Thus it's missing the 'ipam' used in proxy. using https://server.bogus.net/ipam/plugins/nextbox-ui/site_topology/1/ direct in browser renders perfectly.

So, somewhere in the plugin, there is need to look at some parameter defining proxy configuration

Also, it would be good to have a parameter for canvas size, as some of us have seriously big screens:-)

**Comment by iDebugAll** [comment]
> We are running netbox behind a reverse proxy (Traefik) with a URL rewrite. This is how we access Netbox:
> URL: https://server.bogus.net/ipam/

Netbox plugins rely on the same nginx+Django backend. They both should be unaware of this 'ipam' path prefix.
Furthermore, you can only control the */plugins/{plugin_name}/* path address space for the plugin. 

Technically, your reverse proxy should do this rewrite job inside the HTML responses.
Let's say, the Sites link on the Netbox main page looks as follows by default:
```
<h4 class="list-group-item-heading">
  <a href="/dcim/sites/">Sites</a>
</h4>
```
Considering the request flow below (please correct me if it is different), where is the returned HTML '/dcim/sites/' href getting modified to '/ipam/dcim/sites/'? 

Client --"GET /ipam/"--> Traefik --"GET /"-->NGINX+(WSGI)Django-->Netbox
Client <--"200 OK w/ HTML"-- Traefik <--"200 OK w/ HTML"-- NGINX+(WSGI)Django<--Netbox

> Also, it would be good to have a parameter for canvas size, as some of us have seriously big screens:-)

Please create a separate feature request for this.
There are some limitations on dynamic view dimensions in Next UI. I'll try to find a workaround.

**Comment by ziggekatten** [comment]
By using the environment variable BASE_PATH set to ’ipam/’ netbox will honor and append the new path from traefik. https://netbox.readthedocs.io/en/stable/configuration/optional-settings/

However, if you use absolute paths instead of relative in returned html, this variable is useless.

Looking at it, it seems as simple as removing the first ”/” in the <iframe> section in site_topo_button.html

I’ll test it tomorrow.

**Comment by iDebugAll** [comment]
> By using the environment variable BASE_PATH set to ’ipam/’ netbox will honor and append the new path from traefik.

This makes difference.
I have just published a new plugin [v0.4.5](https://pypi.org/project/nextbox-ui-plugin/0.4.5/) release with a suggested fix. Site topology button now renders by Django url template handler. This should work in case of the custom base path as well.
Please upgrade the plugin and check if it helps in your case.

**Comment by ziggekatten** [comment]
I'll test your version. I got it working by using settings.BASE_PATH, but your solution is more Djangoish.

<iframe src="/{{ settings.BASE_PATH }}plugins/nextbox-ui/site_topology/{{ object.id }}/" style="height: 75vh; width: 100%;"></iframe>

**Comment by ziggekatten** [comment]
Works like a charm. THis can be closed as I see it. Sweet!
