### ISSUE TITLE
Nothing popuates in topology viewer

### ISSUE THREAD

**Issue by hooray4me** [iDebugAll/nextbox-ui-plugin#111]
I have a fresh install via docker-compose. I followed the instructions here https://github.com/iDebugAll/nextbox-ui-plugin#installation-with-docker to add the plugin.
I get a blank screen.
![image](https://user-images.githubusercontent.com/12399138/197544056-56e126ee-72e5-431d-9355-157fda8a3e46.png)

I have tried changing the Dockerfile permisisons to various combos of COPY --chown=100:0 --chmod=755, COPY --chown=1000:0 --chmod=755 .... etc

Can anyone point me in the right direction?

**Comment by Qwiko** [comment]
Are you using netbox version 3.3?
See #108

**Comment by hooray4me** [comment]
I installed from https://github.com/netbox-community/netbox-docker

**Comment by iDebugAll** [comment]
Did you select any Sites/Devices/VLANs/etc using Filters tab?
