### ISSUE TITLE
Install fails at migrate

### ISSUE THREAD

**Issue by dywilson73** [iDebugAll/nextbox-ui-plugin#113]
I have just tried installing this plugin using instructions 
here https://docs.netbox.dev/en/stable/plugins/
and 
here https://github.com/iDebugAll/nextbox-ui-plugin

and all goes well until i run 
`python3 manage.py migrate`

i get an error ultimately saying 

`ImportError: cannot import name 'MAX_INT' from 'graphql.type.scalars' (/usr/local/lib/python3.10/dist-packages/graphql/type/scalars.py)`

any ideas?

**Comment by dywilson73** [comment]
I solved this - was running wrong version.

**Comment by pmgeahan** [comment]
> I solved this - was running wrong version.

I'm having this problem as well - can you explain what you mean about running the wrong version?

**Comment by dywilson73** [comment]
> I'm having this problem as well - can you explain what you mean about running the wrong version?

I was not actually running Netbox 3.4.0 at the time. 
Once I upgraded to 3.4.0 it worked.
