### ISSUE TITLE
Server Error - Site 1

### ISSUE THREAD

**Issue by oetti77** [iDebugAll/nextbox-ui-plugin#115]
Hi Guys,

i'm getting the following error while viewing the topology for site 1.
All other sites are working fine. 

```
<class 'IndexError'>

list index out of range

Python version: 3.9.2
NetBox version: 3.4.1
```

**Comment by nbrgit** [comment]
Same Problem - any Ideas?

**Comment by johnrdowson** [comment]
I was receiving the same error in the GUI for a particular site. Looked into it further and found that it was due to a device having a link to a recently deleted device. It was resolved by removing the cable from the relevant interface.
