### ISSUE TITLE
Plugin installation error

### ISSUE THREAD

**Issue by deniskonovalov64** [iDebugAll/nextbox-ui-plugin#121]
Execute these commands:
```
# source /opt/netbox/venv/bin/activate
(venv) # pip3 install nextbox-ui-plugin
```
And it gives me this error:
```
ERROR: Could not find a version that satisfies the requirement netbox-ui-plugin (from versions: none)
ERROR: No matching distribution found for netbox-ui-plugin
```
Can you suggest what can be done in this case?

ubuntu 20.04.5 LTS
```
pyhton3 -V
python 3.8.10
```
```
pip3 -V
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
```

**Comment by deniskonovalov64** [comment]
I'm sorry I was inattentive

**Comment by iDebugAll** [comment]
There is a typo in the plugin name in your `PLUGINS` list. It should be `nextbox-ui-plugin`.

**Comment by deniskonovalov64** [comment]
> `PLUGINS`В вашем списке опечатка в названии плагина . Это должно быть `nextbox-ui-plugin`.

Yes, I saw an error, so I closed this question, but thanks anyway)
