### ISSUE TITLE
Topology Mapping

### ISSUE THREAD

**Issue by deniskonovalov64** [iDebugAll/nextbox-ui-plugin#122]
Good afternoon, please tell me why when building a topology, only the direct connection of one device to another is displayed, and those devices that are connected via passive equipment are not displayed connected?
Is there a way to fix this?

**Comment by PaulR282** [comment]
Same problem. It worked some versions ago. 
I thought setting "DISPLAY_LOGICAL_MULTICABLE_LINKS" to True would fix it but nothing changed.

**Comment by iDebugAll** [comment]
This is reworked in the latest plugin release.
