### ISSUE TITLE
Saved current view

### ISSUE THREAD

**Issue by starinasid** [iDebugAll/nextbox-ui-plugin#123]
good afternoon. there is a problem - when saving through the plugin 0.11.0 ui in topology view. when I view the topology and want to save it, I give it a name - I click Save - it gives a Failed error. I know that this function appeared in version 0.8 of the plugin. but now it doesn't work. what could it be? netbox version 3.3.7

**Comment by rrob666** [comment]
I have encountered the same issue on netbox 3.4.2, and plugin 0.10.0, i hoped it was a bug because of the 3.4.x version of netbox, but it seems it doesn't work on older ones too.

**Comment by starinasid** [comment]
Now at the moment updated to the latest version 3,4,4. The plugin remained the same - 0.11.0. Save error remains. But digging into the netиox log saw an error - Unsupported Media Type: /api/plugins/nextbox-ui/savedtopologies/
![netbox](https://user-images.githubusercontent.com/125595956/220080644-6f9a5b7b-993f-4cc1-89f3-d0841a2107b0.PNG)

**Comment by starinasid** [comment]
#120 helped me
[https://github.com/iDebugAll/nextbox-ui-plugin/pull/120/commits/db761e7e2c38869d2976f9038e92f0eb4918efb4](url)
