### ISSUE TITLE
top level navigation option

### ISSUE THREAD

**Issue by ryanmerolle** [iDebugAll/nextbox-ui-plugin#124]
netbox-community/netbox#9071 added support for plugins to insert top level navigation.

I suggest you set a configurable option for admins to select whether to display in the plugin menu or top level.

Example implementation:
https://github.com/ryanmerolle/netbox-acls/pull/113/files
https://github.com/ryanmerolle/netbox-acls/pull/99/files#diff-5ccb29e85418111d509009d396f8761919501a68b9de65034d85e63cbd38d830

**Comment by iDebugAll** [comment]
This is implemented now in the latest release.
