### ISSUE TITLE
matching query does not exist

### ISSUE THREAD

**Issue by mzsoft27** [iDebugAll/nextbox-ui-plugin#125]
Hi,
Netbox updates were performed, but we have not checked from which version is failing, the problem we have is that we can not see any device.
![image](https://user-images.githubusercontent.com/107618777/225164306-3aa61e85-7e29-4e49-9dcd-def621321eda.png)
the error if I search an any device.
![image](https://user-images.githubusercontent.com/107618777/225164616-da385525-6598-41d7-80b0-264fe1cc42da.png)

I had templates saved but now I can't see them and it shows this error.
![image](https://user-images.githubusercontent.com/107618777/225164712-b3977c04-6283-4423-9c98-cac3f8c67c43.png)
![image](https://user-images.githubusercontent.com/107618777/225164735-f4c79724-14a9-4409-88ff-2f1488bf137a.png)

Could you help me by telling me how to reinstall the plug-in, or if you know how to solve this problem?
Thanks in advance

**Comment by kirillmuravyev** [comment]
I have the same error saying when I open topology of sites with circuit terminations
'CircuitTermination' object has no attribute 'device_id'

**Comment by mzsoft27** [comment]
the problem was all the device are conected with CiruitTermination, you need to eliminate the connection between them or the relationship between them.

**Comment by WhaleJ84** [comment]
Getting the same issue with circuit terminations. Would be nice if the plugin could just ignore the terminations if it doesn't know how to handle them.
