### ISSUE TITLE
[Feature request] Map icons to device roles

### ISSUE THREAD

**Issue by zombah** [iDebugAll/nextbox-ui-plugin#13]
Devices have alot of types like router-x-y-ac, router-x-y-dc and etc etc maping all of them  
not very comfortable because of huge list to map them all and may need frequent additions,  
device roles on the other hand more stable list and lesser size like core-router, edge-router for all routers, so mapping to device roles may simplify overall config file and its housekeeping

**Comment by iDebugAll** [comment]
Thank you for the suggestion. An improved logic is now available in [v0.5.0](https://pypi.org/project/nextbox-ui-plugin/0.5.0/).
The summary of the changes is available in the PR #14 merge commit [caa39c7](https://github.com/iDebugAll/nextbox-ui-plugin/commit/caa39c71586d807d92c79444368f9ea2c1beeb35) description.
