### ISSUE TITLE
fields.E300 error after upgrading Netbox from v3.5.x to v3.6

### ISSUE THREAD

**Issue by litebito** [iDebugAll/nextbox-ui-plugin#137]
Hi,

after upgrading from Netbox v3.5.x to v3.6, I get following error during the upgrade (migration) process:

```
Applying database migrations (python3 netbox/manage.py migrate)...
SystemCheckError: System check identified some issues:

ERRORS:
nextbox_ui_plugin.SavedTopology.created_by: (fields.E300) Field defines a relation with model 'users.AdminUser', which is either not installed, or is abstract.
nextbox_ui_plugin.SavedTopology.created_by: (fields.E307) The field nextbox_ui_plugin.SavedTopology.created_by was declared with a lazy reference to 'users.adminuser', but app 'users' doesn't provide model 'adminuser'.
```

Is this related to any of these changes in NetBox?
https://github.com/netbox-community/netbox/issues/13309
https://github.com/netbox-community/netbox/issues/12794

**Comment by PaulR282** [comment]
Same problem. Plugin does not work with netbox v3.6

**Comment by serberer** [comment]
Same Problem here Netbox v3.6

**Comment by karluum** [comment]
Same problem on 3.6.1

**Comment by alex-gutzeit** [comment]
Same problem 3.6.1

**Comment by litebito** [comment]
it looks like development of this plugin has stalled a bit.... or is it already dead?

**Comment by PaulR282** [comment]
> it looks like development of this plugin has stalled a bit.... ?

Yes, it's quite dead. Go and have a look at mattieserver/netbox-topology-views. It's a great alternative that is beeing updated.
