### ISSUE TITLE
Error in database migration

### ISSUE THREAD

**Issue by NaveenReddy198** [iDebugAll/nextbox-ui-plugin#138]
Hii Team , Iam using Netbox version 3.6.5 and on top of that i wanted to use nextbox-ui-plugin .I have installed it .
While running below command
(venv) $ python3 manage.py migrate
Iam getting below errors
ERRORS:
nextbox_ui_plugin.SavedTopology.created_by: (fields.E300) Field defines a relation with model 'users.AdminUser', which is either not installed, or is abstract.
nextbox_ui_plugin.SavedTopology.created_by: (fields.E307) The field nextbox_ui_plugin.SavedTopology.created_by was declared with a lazy reference to 'users.adminuser', but app 'users' doesn't provide model 'adminuser'.
Can anyone help me with this ?

**Comment by bogdancordos** [comment]
Unfortunately, this plugin is not supported on NetBox 3.6 and above.
I do really hope that the maintainers of this plugin will bring this back as it was best topology tool.

**Comment by TheGuardianLight** [comment]
Same issue for me sadly

**Comment by litebito** [comment]
It seems that development of this plugin has stalled or is dead.
Maybe mattieserver/netbox-topology-views could be an alternative
See also: https://github.com/iDebugAll/nextbox-ui-plugin/issues/137

**Comment by iDebugAll** [comment]
Thanks everyone for you patience. I've just released a compatibility fix for NetBox 3.6, 3.7, and newly released 4.0.
