### ISSUE TITLE
Topology Viewer shows devices & names, but no other information. 

### ISSUE THREAD

**Issue by iColorad0** [iDebugAll/nextbox-ui-plugin#148]
I have installed the plugin and am able to see my site & all devices with the connections. However when I highlight/click on the device, cable; I cannot see any other information such as location(rack,RU,pos) of device, nor the network information of the device at all. Just a blank information box.

**Comment by iColorad0** [comment]
This issue is related with issue #147 , the error was solved via switching to light mode.

**Comment by kprklg** [comment]
So this is not a solution to the problem. It's just working in a different mode. But what about those who work in dark mode?

**Comment by iColorad0** [comment]
I agree, frustrating to say the least as I work in dark mode only in line with my system settings.

**Comment by iDebugAll** [comment]
This is fixed in the latest plugin release.
