### ISSUE TITLE
Display topology in plugin directory, but not in Site directory

### ISSUE THREAD

**Issue by Vadims06** [iDebugAll/nextbox-ui-plugin#15]
Hi. I've installed a plugin on Netbox 2.8.5, followed your guidance, make collect static, etc. I can see topology in plugins/nextbox-ui/site_topology/{site_id}/ but then I pressed Topology button in the site property - I see loading status permanently and see the following errors in the browser logs
Object
links: (2) []
nodes: (40) []
DevTools failed to load SourceMap: Could not load content for https://<domain>/static/nextbox_ui_plugin/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by ziggekatten** [comment]
This trick solved the issue for me. https://github.com/iDebugAll/nextbox-ui-plugin/issues/9
