### ISSUE TITLE
Incomplete cable termination causes topology to crash

### ISSUE THREAD

**Issue by Cyber-Templar** [iDebugAll/nextbox-ui-plugin#154]
Hello there!

It seems to be the problem when trying to display device with existing incomplete cable termination (e.g. when termination A is defined and termination B does not exist)
```
The complete exception is provided below:

<class 'IndexError'>

list index out of range

Python version: 3.12.3
NetBox version: 4.1.4
Plugins: 
  netbox_reorder_rack: 1.1.3
  nextbox_ui_plugin: 1.0.1
```

Incomplete cable terminations may arrive when deleting an adjacent interface (or the entire device).

It might be enough to exclude such connections here:
https://github.com/iDebugAll/nextbox-ui-plugin/blob/6c14c9009861cfe50de8275c12fc93f24d095860/nextbox_ui_plugin/views.py#L432-L441

But there may be a few more places I haven't noticed.

**Comment by iDebugAll** [comment]
Thank you for pointing out the ways to reproduce the bug. I have already found the fix and tested it in my development environment.
