### ISSUE TITLE
Error: "<class 'ValueError'>"

### ISSUE THREAD

**Issue by hb-i** [iDebugAll/nextbox-ui-plugin#16]
Getting this error after installing it and trying to view site topology. Any thoughts?

    <class 'ValueError'>
    not enough values to unpack (expected 2, got 1)

![](https://i.imgur.com/1uS2rF2.png)

**Comment by astruwe** [comment]
Same here:

Not sure if this is related to missing links or many devices.

![image](https://user-images.githubusercontent.com/65309568/85690159-96a56d80-b6d3-11ea-9884-96a814a9b47e.png)

**Comment by hb-i** [comment]
> 
> 
> Same here:
> 
> Not sure if this is related to missing links or many devices.
> 
> ![image](https://user-images.githubusercontent.com/65309568/85690159-96a56d80-b6d3-11ea-9884-96a814a9b47e.png)

Gave it another shot and same error but it was fixed after upgrading from 2.8.0 to 2.8.6. However now the UI looks glitchy and doesn't show the devices.

![](https://i.vgy.me/dEhh7g.png)

**Comment by astruwe** [comment]
Please don't forget to do the last step. I saw this view because I forgot to execute this last line:

`(venv) $ cd /opt/netbox/netbox/
(venv) $ python3 manage.py collectstatic`

**Comment by hb-i** [comment]
> 
> 
> Please don't forget to do the last step. I saw this view because I forgot to execute this last line:
> 
> `(venv) $ cd /opt/netbox/netbox/ (venv) $ python3 manage.py collectstatic`

Yep, I guess I should have made a new reply but I made the edit above after I did exactly that.

**Comment by astruwe** [comment]
My view doesn't load at all. I am on 2.8.6. Some views are working and some are not.
