### ISSUE TITLE
Unselected tags and roles slugs shown although initially deselected in plugin configuration

### ISSUE THREAD

**Issue by astruwe** [iDebugAll/nextbox-ui-plugin#20]
Although I had excluded some device tags and role slugs in my plugin configuration they are shown if the topology view is loaded.

![image](https://user-images.githubusercontent.com/65309568/85690873-48449e80-b6d4-11ea-8c7d-d641efd2b9d3.png)

**Comment by Vadims06** [comment]
@iDebugAll, can you check this. I faced with the same error. I see `layerSelectorByTagOnChange is not defined
    at HTMLInputElement.onchange` error in browser console.

**Comment by iDebugAll** [comment]
@astruwe @Vadims06 

What is your Netbox environment? Did you perform static files update after the plugin upgrade/installation?
Missing function error may occur in case of improperly cached plugin JS files. 
Generally, this should help:

```
$ cd /opt/netbox/netbox
$ python manage.py collectstatic
```

**Comment by astruwe** [comment]
@iDebugAll 

I am using NetBox v2.8.6 on Ubuntu 18.04 LTS.

Using python manage.py collectstatic results in 0 static files copied, 1145 unmodified. Did that after the installation of the plugin.

It seems that not all of the devices with the tag 'patchpanel' are loaded initially but if I select and deselect them all of the 'patchpanels' are gone after that.

How can I help to debug it?

**Comment by iDebugAll** [comment]
@astruwe 

try to perform collectstatic with --clear option. It should delete existing files and then copy everything from scratch:
```
python manage.py collectstatic --clear
```

Optionally, you could try to delete plugin static files manually and perform collectstatic again (this option is more safe):
```
# rm -rf /opt/netbox/netbox/static/nextbox_ui_plugin
# # or 
# rm -rf /opt/netbox/netbox/project-static/nextbox_ui_plugin
# cd /opt/netbox/netbox/
# python manage.py collectstatic --clear
```
