### ISSUE TITLE
Blank page in topo view

### ISSUE THREAD

**Issue by misch42** [iDebugAll/nextbox-ui-plugin#22]
Hi,

I installed everything according to the docs. But when I open the topo view of my test site, it is empty.

I have two switches with a distribution and an access role. In the view I see both roles displayed, but not device itself. Ideas?

**Comment by misch42** [comment]
![Screenshot_nextbox_ui](https://user-images.githubusercontent.com/6481385/86359830-cf17ef00-bc71-11ea-8857-c05132382565.png)

**Comment by misch42** [comment]
the screenshot only shows when I had only one device role

**Comment by Vadims06** [comment]
Did you restart netbox?

**Comment by misch42** [comment]
yes, of course.

**Comment by Vadims06** [comment]
In chrome you can press F12 and go to Console Tab and check errors.

**Comment by misch42** [comment]
There are a lot of "Fail to load resource:  ... button_utils.js ... status 404 (Not Found)"

**Comment by misch42** [comment]
I cloned the project from github and installed it with "pip3 install ."

**Comment by misch42** [comment]
![Screenshot_nextbox_errors](https://user-images.githubusercontent.com/6481385/86361792-a34a3880-bc74-11ea-92fb-905427044d89.png)

**Comment by iDebugAll** [comment]
> There are a lot of "Fail to load resource: ... button_utils.js ... status 404 (Not Found)"
>I cloned the project from github and installed it with "pip3 install ."

Did you do collectstatic after that? All files above has to be hosted by Nginx.
Please try this:

```
$ cd /opt/netbox/netbox
$ python manage.py collectstatic
```

**Comment by misch42** [comment]
ok. I thought that I did that. But it copied another 150 static files. BUT:

Now I see a blue circle of death circeling forever. The console says:

DevTools failed to load SourceMap: Could not load content for https://192.168.88.19/static/nextbox_ui_plugin/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://192.168.88.19/static/nextbox_ui_plugin/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by misch42** [comment]
ok. It seems the the error in the console is not related to the blue circle of death.

**Comment by iDebugAll** [comment]
js.map files error may be ignored in this case. This is only related to development tools. I'll clean this up.

The issue with infinite loading logo refers to #9. It happens in several browsers and/or versions.
There is a [workaround](https://github.com/iDebugAll/nextbox-ui-plugin/issues/9#issuecomment-638464830) to fix this.

**Comment by misch42** [comment]
seems to work now. Thanks for your help
