### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by jpobeda** [iDebugAll/nextbox-ui-plugin#23]
Hi,

If someone clicks on "topology" for a site that has devices but absolutely no connections declared, you get the exception below.

> Server Error
> There was a problem with your request. Please contact an administrator.
> 
> The complete exception is provided below:
> 
> <class 'ValueError'>
> 
> not enough values to unpack (expected 4, got 3)
> If further assistance is required, please post to the NetBox mailing list.

**Comment by iDebugAll** [comment]
Hi @jpobeda, thank you for the bug report. I'll publish a fix soon.

**Comment by Vadims06** [comment]
> Hi @jpobeda, thank you for the bug report. I'll publish a fix soon.

Hi @iDebugAll , I just reinstall your plugin, and I can see topology from several sites, but it strange, but I still get the error on some particular site
The error is:
`<class 'ValueError'>

too many values to unpack (expected 2)`

**Comment by iDebugAll** [comment]
Hi @Vadims06, could you check the browser development console? Are there any additional errors? 
Have you also had a chance to fix the out of sync static files issue mentioned in #20? Please check my last [comment](https://github.com/iDebugAll/nextbox-ui-plugin/issues/20#issuecomment-656281004) there.

**Comment by Vadims06** [comment]
Sadly, but no any additional info. I see just
`Failed to load resource: the server responded with a status of 500 (Internal Server Error)`
My steps were:
I delete plugin folder rm -rf /opt/netbox/netbox/static/nextbox_ui_plugin,
then I clear static 
python manage.py collectstatic --clear
then I go to /opt/nextbox_ui_plugin folder, pull your changes from git `git pull`, `pip install .`, collect static once again and restart netbox
