### ISSUE TITLE
too many values to unpack (expected 2) error

### ISSUE THREAD

**Issue by SerhiiZahuba** [iDebugAll/nextbox-ui-plugin#26]
after open the module i see error 

There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'ValueError'>

too many values to unpack (expected 2)
![image](https://user-images.githubusercontent.com/36307887/87757658-ae27d000-c813-11ea-9ac6-40d131bb0677.png)

netbox (v2.8.7)

**Comment by iDebugAll** [comment]
This issue is fixed by #27.
Please update the plugin and verify if it helped.

**Comment by SerhiiZahuba** [comment]
thanks , after update 0.6.4 - all works fine

**Comment by chiahetcho** [comment]
Thank you!
