### ISSUE TITLE
Display topology for regions

### ISSUE THREAD

**Issue by ChrisdAutume** [iDebugAll/nextbox-ui-plugin#30]
Hi,

In case of big infra, display topology from a region should be nice.

I can prepare a PR for this.

Regards ;p

**Comment by iDebugAll** [comment]
It has been implemented in a slightly different way in the latest plugin release (v0.7.0). 
You can now select arbitrary set of Sites and Regions on a dedicated Topology Viewer page. Please refer to #41 for details.
Feel free to upgrade and test. Your feedback is appreciated.
