### ISSUE TITLE
Missing connections and wrong port labels when passive devices are hidden

### ISSUE THREAD

**Issue by AlbanBedel** [iDebugAll/nextbox-ui-plugin#32]
It seems that hiding passive devices also hide some existing connection. Here is what I see with passive devices shown:

![Screenshot with passive devices](https://user-images.githubusercontent.com/2648902/99185955-51024380-274d-11eb-8220-504aa682a2e5.png)

But if i hide the passive devices the connection between `leuchten-ap` and `kindergarten-sw` is missing:

![Screenshot without passive devices](https://user-images.githubusercontent.com/2648902/99185947-49429f00-274d-11eb-8d88-a94d89ec6a6e.png)

Tracing this connection in netbox work just fine.

Also note that when hiding the passive devices the port name on the `kindergarten-sw` side of the connection to `valentin37-sw` is wrong, it should be `gi1/0/1` as shown when the passive devices are enabled, and not `gi1/0/8`.

**Comment by iDebugAll** [comment]
> It seems that hiding passive devices also hide some existing connection.

This is expected behaviour. However such links should be recalculated and then replaced with direct logical links.
Where does _leuchten-ap_ terminate finally as per cable trace output? Does remote end belong to the same site?

**Comment by AlbanBedel** [comment]
Yes, the remote end belong to the same site, here is the cable trace for the `wan` interface of `leuchten-ap`:
![Leuchten-ap wan cable trace](https://user-images.githubusercontent.com/2648902/99282208-b03a8380-2833-11eb-9bfc-d635a695d757.png)

**Comment by iDebugAll** [comment]
Hi @AlbanBedel. 

Wrong interface label assignment is now fixed in release v0.6.6.

I was also able to reproduce the issue with a missing logical link. Please try to trace the cable 51 or 52 to confirm. It should return just a single segment. The cable to valentin37-sw trace result should return the full path at the same time.
It seems the Netbox trace function returns different result for cables depending on where they were connected from.
I am working on this.

**Comment by iDebugAll** [comment]
Hi @AlbanBedel.

I have published a plugin release v0.6.9 containing the fix for missing logical links issue. It should be backward compatible with Netbox pre-2.10.1 versions. Please try to update the plugin in your environment and let me know if it helps. I'll keep the issue opened for a while.

**Comment by AlbanBedel** [comment]
I finally could test v0.6.9 and I can confirm that both issues are now fixed. Thanks a lot!
