### ISSUE TITLE
Make better use of large displays

### ISSUE THREAD

**Issue by MaxRink** [iDebugAll/nextbox-ui-plugin#33]
Currently the design doesnt scale up on lartger displays, "wasting" a lot of screen real estate.
Example:
![Unbenannt](https://user-images.githubusercontent.com/4894735/101639376-87bb3900-3a2f-11eb-8932-56b56516cfc3.PNG)

**Comment by iDebugAll** [comment]
Hi @MaxRink
I have published a new plugin version which implements a dedicated Topology Viewer page. Topology canvas size is more adjustable there. Feel free to upgrade and test. Your feedback is appreciated.

**Comment by MaxRink** [comment]
That works beautifully, thanks!
