### ISSUE TITLE
Netbox 2.10.1 - plugin not displaying devices

### ISSUE THREAD

**Issue by warriorsoul15** [iDebugAll/nextbox-ui-plugin#38]
I have Netbox 2.10.1 installed and the plugin, however when i click on a site its not showing any devices at all and looks like an incomplete view even of menus based on other screenshots.  I did at device tags to a few devices to see if that was at issue but even those dont show up.

![image](https://user-images.githubusercontent.com/11276980/104821674-796cf380-580b-11eb-8821-a7f3e10eb562.png)

**Comment by iDebugAll** [comment]
Hi @warriorsoul15. What is a plugin version installed on your Netbox? Netbox 2.10.1 is compatible with the latest plugin release (v0.6.9) only.

**Comment by warriorsoul15** [comment]
I am pretty sure it was the latest it was installed via pip3

**Comment by iDebugAll** [comment]
Could you try to execute `$ .manage.py collectstatic` manually? It seems some static JS files are not being served correctly. Do you use bare VM or Docker environment for your NetBox?

**Comment by warriorsoul15** [comment]
I resolved it by fixing a permissions issue for the static export
