### ISSUE TITLE
Configurable Styles

### ISSUE THREAD

**Issue by brotherdust** [iDebugAll/nextbox-ui-plugin#43]
Hi!
Thanks for making this plugin. I've always thought UI was under-utilized and was excited to see this happen!

One suggestion I'd like to make is to make options for more configurable control over the style of the diagram.

For whatever reason, the labels are HUGE on my diagrams, and I'd like to be able to control the font size as well as the colors.

Attached is a picture of what's happening:
![Screenshot](https://user-images.githubusercontent.com/10413016/107973937-18078400-6f73-11eb-9576-335781fc64e4.png)

Is this something you are interested in implementing, or would you prefer a PR? Whatever works best for you.
Thanks!

**Comment by iDebugAll** [comment]
Hi! It looks like a bug. It does not reproduce in my test environment.
An initial font size is 11 and it should autoscale along with a view.
What is your OS and browser version? 
Did you perform `./manage.py collectstatic` after the upgrade? Did you try to clear a browser cache?

**Comment by brotherdust** [comment]
Upgraded to 0.8.1. Fixed. Thanks!
