### ISSUE TITLE
After plugin upgrade v0.6.9 to v0.8.0 topology view not working

### ISSUE THREAD

**Issue by Soeren-FT** [iDebugAll/nextbox-ui-plugin#47]
The plugin was updated with pip3 -install netbox-ui-plugin -U

After restarting the services, no map is displayed after pressing the topology button. The buttons of the plugin are there. 
When clicking on the site name and opening the new view page, the following message appears:

<class 'psycopg2.errors.InvalidCursorName'>
cursor "_django_curs_140410218845952_sync_2" does not exist
Python version: **3.6.9**
NetBox version: **2.10.4**

### Error details:

**[NetBox] ERROR (internal IP): Internal Server Error: /plugins/nextbox-ui/topology/**
Internal Server Error: /plugins/nextbox-ui/topology/

InvalidCursorName at /plugins/nextbox-ui/topology/ cursor "_django_curs_140530272945920_sync_2" does not exist

Did I not do an intermediate step or configuration when updating?

**Comment by iDebugAll** [comment]
Version 0.8.0 introduces a custom database model. Database migrations are distributed with the plugin.
Please try to execute `$./manage.py migrate` manually.

**Comment by Soeren-FT** [comment]
Thanks for the reply. This command fix the issue in my installation.
Is it normal that the topology is no longer visible in the pop window?

**Comment by iDebugAll** [comment]
>Thanks for the reply. This command fix the issue in my installation.

Great. I updated a project readme accordingly. 

>Is it normal that the topology is no longer visible in the pop window?

It is not. Please try to execute `$./manage.py collectstatic --clear` and clear your browser cache.

**Comment by Soeren-FT** [comment]
It works! 
Thank you for the quick and excellent support.

Have a nice day.
