### ISSUE TITLE
Setting 'undisplayed_device_role_slugs' is ignored on load

### ISSUE THREAD

**Issue by heiko-ma** [iDebugAll/nextbox-ui-plugin#54]
**Netbox version:** 2.10.6
**Python version:** 3.6.8

If the config-setting '**undisplayed_device_role_slugs**' is defined as stated in the documentation, the configured device roles are still being displayed on inital load.
I discovered that the checkboxes of the configured device roles get unselected so the config setting itself works, but the action does not. When you select and unselect the device role afterwards, the nodes with that specific roles disappear like they are supposed to.
If you need my logs or config files, i'm happy to provide them.

**Comment by nahun** [comment]
Pasting your config may help.

I had the same problem I think. I switched the value from a tuple to a list and it works now. At least I'm pretty sure that was the problem. It doesn't make sense to me why that would help though.

```python
'undisplayed_device_role_slugs': [
    'mgmt-sw'
],
```
