### ISSUE TITLE
Feature Request: Filter by Location

### ISSUE THREAD

**Issue by dreng** [iDebugAll/nextbox-ui-plugin#57]
The upcoming netbox release (v2.11) renames "Rack Groups" to "Locations". It will be possible to nest Locations (as you can with current Rack Groups). Furthermore it will be possible to assign non-racked devices to Locations (which is not possible with current Rack Groups in v2.10).

Side note: Locations are useful to organize sections within a site. E.g. it can be a room, a floor, a department containing nested rooms, a corridor, a production hall with sections nested underneath that Location, etc.

![2021-04-08 10_40_21-Window](https://user-images.githubusercontent.com/20901110/113997575-950af780-9858-11eb-9000-3e3cd0d45b87.png)

I'd suggest to add Locations to the filter pane in order to show only one or some Locations. Additionally a checkbox will be very handy in order to be able to show a Location and all of its nested children.

![2021-04-08 10_45_42-Window](https://user-images.githubusercontent.com/20901110/113997605-9b996f00-9858-11eb-8f28-aa51a56a04d1.png)

**Comment by iDebugAll** [comment]
Hi @dreng 
Thank you for your suggestion and a pull request. Such use case looks reasonable and helpful.
I have accepted your PR and merged it into master. This feature is now available in the latest plugin release.
