### ISSUE TITLE
Topology & Graphs Buttons

### ISSUE THREAD

**Issue by RHuehne** [iDebugAll/nextbox-ui-plugin#60]
After installing the plugin (0.8.1 / 2.11 with docker), I am missing one Button (Graphs) that should appear on the site page, visible on this image:
https://github.com/iDebugAll/nextbox-ui-plugin/raw/master/samples/sample_topology_button.png

On the new Location Page, I have neither of these Buttons.

Also, the Site Topology View is quite useless for us unless we can break this much more down:
![image](https://user-images.githubusercontent.com/13745200/120458384-8859da00-c397-11eb-931f-1cfb29c3d5fc.png)

Wouldn't it be possible to trigger topology view from a cable trace? 

Thanks,
R.

**Comment by iDebugAll** [comment]
Hi @RHuehne 

`Graphs` button does not belong to this plugin. It is NetBox internal feature (if it is still there).

For large `Sites`, Horizontal/Vertical layout along with Layers Selector may provide some better visibility.
I would recommend to use `Topology Viewer` page in such cases as is allows you to utilise more screen space for a visualization.

`Topology` button has originally been implemented on the `Site` pages only.
Adding this to the `Location` page may be helpful thought. I will consider this in a future releases.
