### ISSUE TITLE
Issue with latest release and Netbox v2.10.1

### ISSUE THREAD

**Issue by aslater3** [iDebugAll/nextbox-ui-plugin#63]
After install of the plugin and restarting services we get the following issue:

ImportError: cannot import name 'Location'

I dont think location was added to the model in this version? Its still rack groups?

**Comment by iDebugAll** [comment]
Hi @aslater3
Sure, my bad. RackGroups turned into Locations in NB 2.11.
I added a fix in a plugin to workaround this issue. Please try to update to v0.8.2.
The filter name will still be displayed as 'Location' but it should display your Rack Groups if any.
