### ISSUE TITLE
NetBox v3.0-beta1 Support

### ISSUE THREAD

**Issue by ryanmerolle** [iDebugAll/nextbox-ui-plugin#66]
As an FYI here is what changed that could impact or help the plugin:
- HTML Template updates (support change from bootstrap 3 to bootstrap 5)
- Overall UI tweaks
- Custom Queue Support for Plugins netbox-community/netbox/issues/6651

If you find any issues or have any questions feel free to hit us on the slack or add a bug /issue or add to the umbrella UI issue netbox-community/netbox/issues/6797

**Comment by maxzapp** [comment]
Is this plugin working with 3.0.3

**Comment by iDebugAll** [comment]
NetBox 3.0.X and 3.1.X support has been implemented.
