### ISSUE TITLE
Feature Request: Publish to PyPi

### ISSUE THREAD

**Issue by ryanmerolle** [iDebugAll/nextbox-ui-plugin#8]
# Feature Request: Publish to PyPi

## Reason:

Publishing to PyPi would allow users to update this plugin using pip & automatically via the NetBox upgrade process when it is added to the local-requirements.txt file in the NetBox directory.

**Comment by iDebugAll** [comment]
The Plugin has been published to PyPi: https://pypi.org/project/nextbox-ui-plugin/
