### ISSUE TITLE
Add Trunk All ports and connexions on VLAN Topology 

### ISSUE THREAD

**Issue by Naideus** [iDebugAll/nextbox-ui-plugin#83]
Hello Mister the creator of this superb plugin 

When we choose vlan filter to show topology VLAN we didn't have trunk all port.
I customize my views.py to integrate it.  (line 239)

    interfaces = vlan.get_interfaces()
    interfaces2 = Interface.objects.filter(mode='tagged-all')
    filtred_devices = [d.id for d in nb_devices_qs]
    filtred_interfaces = []
    for interface in interfaces:
        if interface.is_connectable:
            direct_device_id = interface.device.id
            interface_trace = interface.trace()
            if len(interface_trace) != 0:
                termination_b_iface = interface_trace[-1][-1]
                connected_device_id = termination_b_iface.device.id
                if (direct_device_id in filtred_devices) or (direct_device_id in filtred_devices):
                    filtred_interfaces.append(interface)

    for interface2 in interfaces2:
        if interface2.is_connectable:
            direct_device_id = interface2.device.id
            interface2_trace = interface2.trace()
            if len(interface2_trace) != 0:
                termination_b_iface = interface2_trace[-1][-1]
                connected_device_id = termination_b_iface.device.id
                if (direct_device_id in filtred_devices) or (direct_device_id in filtred_devices):
                    filtred_interfaces.append(interface2)

    devices = []
    for interface in filtred_interfaces:
        if interface.is_connectable:
            if interface.device not in devices:
                devices.append(interface.device)
            interface_trace = interface.trace()
            if len(interface_trace) != 0:
                termination_b_iface = interface_trace[-1][-1]
                if termination_b_iface.device not in devices:
                    devices.append(termination_b_iface.device)

I think you can integrate it (code) better than me.

Thanks again for you work it's amazing

Bien à vous.

**Comment by renatoalmeidaoliveira** [comment]
Hello @Naideus, 

    For a switch a "trunk all" port means all VLANS in that SW vlan database, but the device on netbox doesn't have a vlan database model, so by doing that you really can't know if that "trunk all" allow the filtred vlan on the query, and so your plot might have a lot of wrong devices and links, that's the same point in this discussion on [Netbox discussions](https://github.com/netbox-community/netbox/discussions/5702).
  In my netbox implementation I never use the "trunk all" mode, I prefer to map all the vlans on the DB and add each one on the interface, and imho  I think that's a better way to deploy because on the vlan model I always can see the interfaces associated to a VLAN.
  About the implementation @iDebugAll what do you think, if i was implement that feature I would go for itertools.chain with something like this:
```
interfaces = itertools.chain(
                                   vlan.get_interfaces(),
                                   Interface.objects.filter(mode='tagged-all')
                    )

```
and keep the rest of the code.

**Comment by Naideus** [comment]
Malo @renatoalmeidaoliveira 
thanks for your optimisation and your answer. 
I agree with your point of view. The best way is never use  "Trunk All".

Have a good day
Regards
