### ISSUE TITLE
Topology loading stuck with infinite loading logo

### ISSUE THREAD

**Issue by tommydpl** [iDebugAll/nextbox-ui-plugin#9]
I tried to use Your plugin with the default configuration. For a small site with few (8) devices I've got some result but for a site with over 100 objects the map is never displayed (I waited like 10 minutes) . Also I do not see a way to include only few selected device roles

**Comment by jordanrvillarreal** [comment]
I've had similar issues.  I've found that if you let it sit for a few minutes, no real handle on how long this is, then toggle between the horizontal or vertical view a few times, no real handle on how many times, it will eventually display.  I don't have a site quite at that scale but this work on my site of ~35 devices.

**Comment by iDebugAll** [comment]
First of all, thank you for your feedback.
Please try a few workarounds to identify the issue scope and conditions:
1. Open the Site topology page directly:
http://{your_netbox_host}/plugins/nextbox-ui/site_topology/{site_id}
Will the topology open properly in this case?
2. Add a plugin option to disable initial vertical layout in Netbox’s configuration.py and restart NetBox service:
```
PLUGINS_CONFIG = {
  ‘nextbox_ui_plugin’: {
    ‘INITIAL_LAYOUT’: ‘auto’,
  }
}
```
This should still generate a proper view from the Site page. Once you see the topology, you may switch the layout to vertical/horizontal using buttons manually. 

Also what is your browser and OS? It seems the initial vertical layout pease of code causes the issue with infinite loading logo in some browsers/versions.

**Comment by jpobeda** [comment]
I've seen the same behavior. If I set `INITIAL_LAYOUT` to `auto` it works and If I got straight to  the [URL  ](http://your_netbox_host/plugins/nextbox-ui/site_topology/site_id ) it never fails.

@iDebugAll ,do we have any tools to control node spacing? vertical and horizontal layout get all devices squeezed together. Any chance of saving the positioning once you move them around?
Also on the samples you provide I noticed the labels some times get rendered upside down, how can we get around that?

**Comment by Pzharyuk** [comment]
PLUGINS_CONFIG = {
  ‘nextbox_ui_plugin’: {
    ‘INITIAL_LAYOUT’: ‘auto’,
  }
}


Jun 15 10:27:51 dtnaacvdl210 gunicorn[31768]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
Jun 15 10:27:51 dtnaacvdl210 gunicorn[31768]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
Jun 15 10:27:51 dtnaacvdl210 systemd[1]: netbox.service: main process exited, code=exited, status=1/FAILURE
Jun 15 10:27:51 dtnaacvdl210 systemd[1]: Unit netbox.service entered failed state.
Jun 15 10:27:51 dtnaacvdl210 systemd[1]: netbox.service failed.
lines 14017-14072/14072 (END)

When I add the plugin config, netbox service fails to start.

**Comment by Vadims06** [comment]
> PLUGINS_CONFIG = {
> ‘nextbox_ui_plugin’: {
> ‘INITIAL_LAYOUT’: ‘auto’,
> }
> }
> 
> Jun 15 10:27:51 dtnaacvdl210 gunicorn[31768]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
> Jun 15 10:27:51 dtnaacvdl210 gunicorn[31768]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
> Jun 15 10:27:51 dtnaacvdl210 systemd[1]: netbox.service: main process exited, code=exited, status=1/FAILURE
> Jun 15 10:27:51 dtnaacvdl210 systemd[1]: Unit netbox.service entered failed state.
> Jun 15 10:27:51 dtnaacvdl210 systemd[1]: netbox.service failed.
> lines 14017-14072/14072 (END)
> 
> When I add the plugin config, netbox service fails to start.

Replace ' to "

**Comment by misch42** [comment]
ok. seems to work now. Thanks for your help.

**Comment by iDebugAll** [comment]
INITIAL_LAYOUT is now set to 'auto' by default in the latest release.
This is a workaround setting until a manage to fix the bug.
