### ISSUE TITLE
Does this work with Netbox version 3.1.5?

### ISSUE THREAD

**Issue by bigbearct** [iDebugAll/nextbox-ui-plugin#92]
HI 

Does this work with Netbox version 3.1.5 or 3.1.7?

Cant seem to install it ..

**Comment by PaulR282** [comment]
I use it in the newest 3.2.0 Beta Version and it also works in 3.1.X. What exactly is your problem?

**Comment by andrewm659** [comment]
I'm not seeing the option in the UI to get the topology map.

**Comment by notyettested** [comment]
works in 3.1.5 for me

**Comment by PaulR282** [comment]
> I'm not seeing the option in the UI to get the topology map. I'm trying to run it on 3.1.7

Have you enabled the plugin in the `configuration.py`? Do you see the plugins menu on the left?

**Comment by andrewm659** [comment]
I have enabled it in the configuration.py.  I do not see it in the WebUI.  Screenshots:
![Screenshot from 2022-02-24 10-43-26](https://user-images.githubusercontent.com/6283323/155568850-b6fc9532-2bb6-4de6-aa56-fcd42963be20.png)
![Screenshot from 2022-02-24 10-42-52](https://user-images.githubusercontent.com/6283323/155568853-b93442b7-4bb2-4a2e-9a00-b8e0916d400f.png)

**Comment by ekrichbaum** [comment]
Did you restart the gui? systemctl restart netbox
