### ISSUE TITLE
Missing jquery file

### ISSUE THREAD

**Issue by nikzeyn** [iDebugAll/nextbox-ui-plugin#95]
The source code tries to get ```jquery-3.4.1.min.js``` but it is not in that folder under ```master``` branch.
Error thrown in django:
```"GET /static/nextbox_ui_plugin/jquery/jquery-3.4.1.min.js HTTP/1.1" 404 1758```

I think it needs to be added to the specified directory.

**Comment by ekrichbaum** [comment]
shouldn't that be 3.6 if is is needed?

**Comment by nikzeyn** [comment]
I don't know much about jquery but It seems 3.6 is the latest version and I guess it would be great to have it. I though maybe the code uses v3.4 for backward-compatibility.

**Comment by iDebugAll** [comment]
This is cleaned up and deprecated now.
