### ISSUE TITLE
Multiple interface labels overlap/block each other

### ISSUE THREAD

**Issue by nikzeyn** [iDebugAll/nextbox-ui-plugin#96]
When there are more than one link (curved links) between two devices, the interface labels cover each other so it becomes hard to read. Any idea why it might be and what part of code I can look at to play with/correct it?

**Comment by ocalaf-unitenic** [comment]
I can confirm that issue, it would be nice to have a fix, a workaround or to know where should we investigate to find a solution ourselves

**Comment by Mindl-dev** [comment]
Found a fix for this.

In next_app.js in static/next_ui_plugin, add this at line 320:

var _offset = this.getOffset();
var n = line.normal().multiply(_offset);

Change line 326 to:

point = line.start.add(n);

Change line 337 to:

point = line.end.subtract(n);

Its doesn't look perfect, but it works.

![Capture](https://github.com/iDebugAll/nextbox-ui-plugin/assets/26661685/8c96e206-fe01-474f-a565-b0532b2b0099)

**Comment by nikzeyn** [comment]
Great! Thanks for the solution!
