### ISSUE TITLE
Netbox 3.2 Support

### ISSUE THREAD

**Issue by ryanmerolle** [iDebugAll/nextbox-ui-plugin#98]
[NetBox 3.2.0](https://github.com/netbox-community/netbox/releases/tag/v3.2.0) was just released and has a number of [extension improvements](https://github.com/netbox-community/netbox/issues/8333).

Furthermore, a [NetBox 3.2 plugin tutorial](https://github.com/netbox-community/netbox-plugin-tutorial) was released

**Comment by pdenessen** [comment]
Is this issue not resolved in V0.10.0 ?

**Comment by ryanmerolle** [comment]
this was raised before it and never closed.
