### ISSUE TITLE
Netbox_ui _plugin device icon always renders as question mark (Help)

### ISSUE THREAD

**Issue by HOUDAoah** [iDebugAll/nextbox-ui-plugin#99]
i've installed Netbox_ui_Pling in netbox latest version 3.2.1 every thing work fine until i add a device to my topology . the device allways renders as the defaut question mark !!
![image](https://user-images.githubusercontent.com/104080488/165088482-7e49a44c-2da1-4c78-b6ea-bc57264704fc.png)

1- i install the plugin with enabling the plugin and adding plugin configuration in configuration.py (nothing goes wrong! )
![image](https://user-images.githubusercontent.com/104080488/165089099-098d42e9-5db8-417b-9bd1-e4595a46274f.png)
![image](https://user-images.githubusercontent.com/104080488/165088815-aed44a14-f7d0-406f-b971-cddec8d6397b.png)
2- I collect the static file and apply the data migration (nothing goes wrong !)
3- then finally I restart netbox service (nothing goes wrong!)

please can someone help me

**Comment by iDebugAll** [comment]
What are device `model` and `role` assigned to R1 in your environment?

**Comment by HOUDAoah** [comment]
Hi,
Thank you sir i solved the probleme the device role i created to the router R1 is router which is not declared in the configuration part in configuration.py so i added (router,switch,firewall) that i need 
thank you again for your help.
